// root
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const ENABLE_MODAL = 'ENABLE_MODAL';
export const DISABLE_MODAL = 'DISABLE_MODAL';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

//Profile
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_AVATAR_REQUEST = 'UPDATE_PROFILE_AVATAR_REQUEST';

//Ordering
export const ORDERING_SETTINGS_RESPONSE = 'ORDERING_SETTINGS_RESPONSE';
export const ORDERING_SETTINGS_REQUEST = 'ORDERING_SETTINGS_REQUEST';
export const BILL_NUMBERING_UPDATE = 'BILL_NUMBERING_UPDATE';
export const DELETE_SEATING_ARRANGEMENT = 'DELETE_SEATING_ARRANGEMENT';

//Categories
export const CATEGORIES_RESPONSE = 'CATEGORIES_RESPONSE';


